### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#116]
There are many css classes that are not being used in the project you can find that out and can delete it from the project. 

The level of this issue will depend upon the number of lines removed from the css files 

Steps
1. Delete the css that is not being used in the project
2. Check if the project has still the same UI

**Comment by cryptofox17** [comment]
Could you assign this issue to me please?

**Comment by ArunTeltia** [comment]
Yeah @cryptofox17 go for it

**Comment by ArunTeltia** [comment]
If there are some unused classes then you can delete it, Just check The Ui dont break after deleting those class ✨

**Comment by kanishkaa24** [comment]
Hello! Can i work on this ?

**Comment by ArunTeltia** [comment]
Yeah Sure Find the css which are not being used within the site ,delete it and create a PR

**Comment by RahulBansal0502** [comment]
@rhythmjayee @ArunTeltia I want to work on this issue please assign it to me. I am a GSSOC2021 participant.

**Comment by ArunTeltia** [comment]
Yes go for it let me know if you have any problems

**Comment by RahulBansal0502** [comment]
Ok fine

**Comment by ArunTeltia** [comment]
@cryptofox17 can you remove those bootstrap files as well if you have time, we discussed and we came to conclusinon that we dont need those files 

Delete every instance of css that are not being used in the project

**Comment by cryptofox17** [comment]
@ArunTeltia ok I'll do that

**Comment by ArunTeltia** [comment]
Thank You so much @cryptofox17 🙌
