### ISSUE TITLE
Refractor the html page 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#117]
There are many page which have more than 1 css files integreted 
and other than that style is also being added in the html pages as well 
Remove the style from the page and add them to one of the css file used in the project,

Same for script just create one new script and put all the code inside the script tag into that file

**Comment by Shivam-Shandilya1** [comment]
Can I also work on this issue as Gssoc Participant?

**Comment by ArunTeltia** [comment]
go for it @Shivam-Shandilya1

**Comment by LordShenron** [comment]
Marking the assigned issue.

**Comment by Shivam-Shandilya1** [comment]
Okay !

**Comment by Tanvir397** [comment]
Can I work with this issue

**Comment by Tanvir397** [comment]
Can I work on this as GSSOC participant

**Comment by LordShenron** [comment]
I am not sure if two participant can work on one single issue @ArunTeltia

**Comment by ArunTeltia** [comment]
@Tanvir397 This issue is been assigned to @Shivam-Shandilya1 you can work on #118 if you want to

**Comment by Shivam-Shandilya1** [comment]
I had made two pull request. Please preview it and help me to improve my work experience.
