### ISSUE TITLE
Upgrade the model of the bootstrap from 3 to 4 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#118]
In this project we are using bootstrap for the models and jquery for opening those models, 

The task is to delete the code and refractor it for bootstrap 4 such that the code does not break in the website

**Comment by Shivam-Shandilya1** [comment]
Can I work on this Issue as a GSSOC participant?

**Comment by ArunTeltia** [comment]
Lets focus on 1 issue at a time @Shivam-Shandilya1

**Comment by Tanvir397** [comment]
Can I work on this project

**Comment by ArunTeltia** [comment]
Yes You can work on this issue @Tanvir397  I am assigning this issue to you

**Comment by gaulghost** [comment]
Is this issue completed?

**Comment by ArunTeltia** [comment]
I dont think @Tanvir397 is working on this issue, @gaulghost want to work on this ?

**Comment by gaulghost** [comment]
@ArunTeltia Yes, I wish to work on this issue

**Comment by ArunTeltia** [comment]
This is level 4 that means there are alot of files that need to be changed so it will need to create 4-5 sub issues for solving this issue, If you need any help you can ping me on discord 
@gaulghost go for it 🙌

**Comment by gaulghost** [comment]
@ArunTeltia Yeah sure, will ping you on discord if i face problem.

**Comment by ArunTeltia** [comment]
I dont think we need this anymore when contributor section will be build closing this issue
