### ISSUE TITLE
Refractor the scripts 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#119]
There are many script that are being reused a lot of times find them out and report them 

Reporting the issue will also be level 1 issue resolve

The level of the issue will depend on the difficulty of it

**Comment by Abhi-1313** [comment]
please assign me that

**Comment by ArunTeltia** [comment]
Okay @Abhi-1313 Assigning this issue to you as well,

**Comment by ArunTeltia** [comment]
Any movement here @Abhi-1313 if not, @cryptofox17 want to work on this

**Comment by Preeti2095** [comment]
i want to work on this issue.

**Comment by ArunTeltia** [comment]
If you want to work on it @Preeti2095 go for it assigning the issue, let me know if you have any problems proceeding further 
all the best

**Comment by Preeti2095** [comment]
Thank you @ArunTeltia. Can you elaborate where to look for the scripts , and how to make a report like in doc or something else?

**Comment by ArunTeltia** [comment]
They are in the js folder @Preeti2095 create a documentation for each script on what the script is doing there are also many script that are bieng used several times so for those script we need to DRY them

**Comment by ArunTeltia** [comment]
If you still have doubts ping me on discord will try to resolve your issues 
All the best

**Comment by Preeti2095** [comment]
Ok @ArunTeltia.
