### ISSUE TITLE
UI issue within the websites

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#120]
If you see any UI issue in the website report it by creating an issue that will be counted as level 1 issue(If its a valid issue)

**Comment by yasharth291** [comment]
I am assigning this issue to @SainathPoojary

**Comment by yasharth291** [comment]
please comment on this issue @SainathPoojary

**Comment by SainathPoojary** [comment]
I want to Fix the sticking edge, Please Assign it to me

**Comment by yasharth291** [comment]
you have to change the whole UI faults and do the work on it please mention the points you are going to change the UI of the project
