### ISSUE TITLE
Adding Animations on clicking buttons on navbar.

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/ProjectSakura.github.io#122]
I want to add Animation effects to the navbar buttons when they are clicked. This will make the user experience even better.

**Comment by FireQueen-3010** [comment]
Please assign me this.

**Comment by ArunTeltia** [comment]
Hmmm Can you give an example on what animation you are thinking of adding @FireQueen-3010

**Comment by FireQueen-3010** [comment]
For example: when the button is clicked by a user, the button text gets filled (from one corner to another) with one of the theme colors used in the website (like the ones used in the name Sakura on the homepage).

**Comment by ArunTeltia** [comment]
Yeah sounds good to me I am assigning this issue to you

**Comment by ArunTeltia** [comment]
@FireQueen-3010 Are you working on this if yes can you check the ui theme we just added on readme.md so that you can get an idea on how we want button to look like

**Comment by FireQueen-3010** [comment]
Okay
