### ISSUE TITLE
Adding contact section on the page.

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/ProjectSakura.github.io#123]
The website needs a contact section.

**Comment by FireQueen-3010** [comment]
Please assign me this.

**Comment by FireQueen-3010** [comment]
Please may I know which level would this be?
Also, it will be great if I am given the contact details of the main admins whose contact details are to be displayed on the contact section. We can get connected on Discord if displaying here in comments seems inappropriate. My discord UserName:  Diksha-3010

**Comment by FireQueen-3010** [comment]
Hi, do I add the images in the contact section as well or skip it?

**Comment by FireQueen-3010** [comment]
Hey, I've made the pull request with the required changes.  I have a tiny doubt, please do clarify it. Adding the contact section counts as a small feature of the page and according to gssoc'21 guidelines, as far as I am concerned it comes under level 2. Do you think, it would be worth increasing the issue's level? Hope you consider this and I will glad whatsoever would be your decision. Thank you again!

**Comment by ArunTeltia** [comment]
Sorry for the delay @FireQueen-3010, I have answered your query on 134 PR you can have a look at it,

**Comment by FireQueen-3010** [comment]
Yeah, I've seen it. Thank you again!
