### ISSUE TITLE
UI design and logos

### ISSUE THREAD

**Issue by 24sristi** [ProjectSakura/ProjectSakura.github.io#124]
I'd like to make the logos for the site and also work on the UI

**Comment by kanishkaa24** [comment]
Hello! Can i work on this ?

**Comment by DevrajDC** [comment]
> Hello! Can i work on this ?

We are already working on it.

**Comment by LordShenron** [comment]
@ArunTeltia there is no progress on this issue.. we should close it down.

**Comment by ArunTeltia** [comment]
@LordShenron I dont think either, we have many logos due to @cryptofox17 , and rebranding now is foolish closing this issue as well
