### ISSUE TITLE
Reworking the stat page and adding some important stats too.

### ISSUE THREAD

**Issue by yasharth291** [ProjectSakura/ProjectSakura.github.io#126]

**Comment by saumyasrivastava08** [comment]
Can you explain it more I want to work on this issue.

**Comment by yasharth291** [comment]
there is one stat page you have to come with an idea where you can improve the UI and bring some new stat that you can think of

**Comment by LordShenron** [comment]
I feel this is atleast a level 3 issue.

**Comment by yasharth291** [comment]
yeah sure thank for changing the level of this issue

**Comment by tanishq-arya** [comment]
I have an idea of keeping the page simple by using a bootstrap theme. Like this maybe.
![image](https://user-images.githubusercontent.com/77333275/110753254-5fc8b500-826c-11eb-8f33-a4391ba7d832.png)

**Comment by saumyasrivastava08** [comment]
@yasharth291 Can i work on this?

**Comment by yasharth291** [comment]
you can work but you have to tell which are the extra stats you are going to add in it 
@saumyasrivastava08

**Comment by tanishq-arya** [comment]
Can I work on the design I have provided ?

**Comment by LordShenron** [comment]
> I have an idea of keeping the page simple by using a bootstrap theme. Like this maybe.
> ![image](https://user-images.githubusercontent.com/77333275/110753254-5fc8b500-826c-11eb-8f33-a4391ba7d832.png)

I really like this design.. go ahead.

**Comment by yasharth291** [comment]
but we should add some more stats may be @saumyasrivastava08  she can do this. So we can assign this to them both. One for design and one for adding some ideas for other stats

**Comment by LordShenron** [comment]
The stats are being fetched from sourceforge. They provide total stats, stats for per folder, countries and which operating system was used to download. 

Currently all these stats are already there so there is nothing else to do other than redesigning and maybe fixing up the scripts used for fetching stats so they could work more efficiently.

**Comment by saumyasrivastava08** [comment]
> The stats are being fetched from sourceforge. They provide total stats, stats for per folder, countries and which operating system was used to download.
> 
> Currently all these stats are already there so there is nothing else to do other than redesigning and maybe fixing up the scripts used for fetching stats so they could work more efficiently.
> 
> So, I feel you can change the topic from adding more stats to reworking the scripts used.

I can do the changing in the designing and will add more stats (what you will suggest) can I?

**Comment by LordShenron** [comment]
> I can do the changing in the designing and will add more stats (what you will suggest) can I?

You cannot add more stats because the api don't have anything else to be added..

**Comment by saumyasrivastava08** [comment]
> > I can do the changing in the designing and will add more stats (what you will suggest) can I?
> 
> You cannot add more stats because the api don't have anything else to be added..

So I can change the design?

**Comment by LordShenron** [comment]
Try doing that.. For now I am assigning this issue to both of you.

**Comment by saumyasrivastava08** [comment]
Okay I am doing it

**Comment by tanishq-arya** [comment]
@saumyasrivastava08 I have created a design and it is complete. Could you look at that ? We both have been assigned the issue so maybe we can take it from there. Check the stats-ui branch in my repository of the project.

**Comment by LordShenron** [comment]
This issue is completed for now. 
Refer to this commit for changes: https://github.com/ProjectSakura/ProjectSakura.github.io/commit/0a712d9f4fd25d92dc6ab29c52f0770ac979da5d

Closing it now.
