### ISSUE TITLE
UI Issue: Hover issue

### ISSUE THREAD

**Issue by tanishq-arya** [ProjectSakura/ProjectSakura.github.io#127]
When you hover over the cards the cursor should change to pointer.
![image](https://user-images.githubusercontent.com/77333275/110738065-a14d6600-8254-11eb-8b75-f08caf2daf7c.png)

**Comment by tanishq-arya** [comment]
And the images should open in a new tab if we click on them. I would like to work on this issue under GSSOC. Please assign me this if you find it a valid issue.

**Comment by yasharth291** [comment]
i have assigned you these and hope for an merge request soon

**Comment by tanishq-arya** [comment]
![Screenshot (946)_LI](https://user-images.githubusercontent.com/77333275/110744371-95b36c80-825f-11eb-8a8e-ebc5332ea7a2.jpg)
To give a contrast over the dark background I also changed the box shadow color to white. I have opened a pull request for the same.

**Comment by LordShenron** [comment]
@ArunTeltia can close this issue now
