### ISSUE TITLE
UI Issue : Text Sticking Edges

### ISSUE THREAD

**Issue by SainathPoojary** [ProjectSakura/ProjectSakura.github.io#130]
In Mobile Devices Text Sticks on the edges.

![Screenshot (983)_LI](https://user-images.githubusercontent.com/53347682/110748075-407a5980-8265-11eb-94ad-443616efd724.jpg)

 Hey @yasharth291, I would like to work on this issue under GSSOC. Please assign me this if you find it a valid issue.

**Comment by yasharth291** [comment]
It will be solved while doing #120  if you are able to do that i am happy to assign you that

**Comment by SainathPoojary** [comment]
Yes, I will do it.

**Comment by yasharth291** [comment]
sure i am closing this issue and assigning you the #120
