### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [ProjectSakura/ProjectSakura.github.io#131]
Hi! I would like to add contributing.md to the repo which states on how to clone and fork the repo,how to add ,create and push a repo,squash commits,rebase your feature branch ,how to update forked repo as well as local repo to the changes made in upstream.
I would like to work on this under GSSOC'21.

**Comment by LordShenron** [comment]
@ArunTeltia @yasharth291 
I don't think this is needed for us. Close this issue if you agree.. discuss more further it's needed..

**Comment by ArunTeltia** [comment]
I think it will boost the morale for the contributors tho me and @yasharth291 are thinking of creating a website to showcase the contributors hard work

**Comment by khareyash05** [comment]
@ArunTeltia shall I go with it?

**Comment by ArunTeltia** [comment]
I think for now we should create a contribute.md @khareyash05 assigning this to you

**Comment by khareyash05** [comment]
Thank You!
Could you please add a GSSOC label to the issue
