### ISSUE TITLE
Redesigning the UI for blog posts

### ISSUE THREAD

**Issue by LordShenron** [ProjectSakura/ProjectSakura.github.io#137]

**Comment by cryptofox17** [comment]
could you please assign this to me?

**Comment by LordShenron** [comment]
Think you can redesign all of them while preserving the articles?

**Comment by cryptofox17** [comment]
I just need to work on the CSS to improve the UI of blog posts right?

**Comment by yasharth291** [comment]
yeah mainly that and if you want to add some more of the things you should confirm them with the @LordShenron  and add them

**Comment by cryptofox17** [comment]
Ok then I can do that. Please assign me this issue

**Comment by yasharth291** [comment]
carry on it is assigned to you
