### ISSUE TITLE
Changing buttons on all pages except navbar with dedicated animations and forming uniformity with respect to UI design provided in the readme file.

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/ProjectSakura.github.io#147]
The buttons on the homepage need uniformity in accordance with the UI theme provided in the readme file. It needs dedicated animations as well to make it feel better.

**Comment by FireQueen-3010** [comment]
Please assign me this.

**Comment by ArunTeltia** [comment]
Done @FireQueen-3010  :)

**Comment by FireQueen-3010** [comment]
Thank you!
