### ISSUE TITLE
UI Feature : Redesign navbar on all pages.

### ISSUE THREAD

**Issue by dcs-soni** [ProjectSakura/ProjectSakura.github.io#148]
Hii,

Adding underlines to the navbar menus while hovering gives the website a pure look and the page looks decent with the underline animations. If you like this idea please assign this feature request to me under **GSSoC'21**.

Below is the screenshot of my idea. Any suggestions to change the color or any modifications are appreciated.
 

https://user-images.githubusercontent.com/52232900/111069660-1ee2d180-84f4-11eb-9e32-3746bd81e649.mp4

**Comment by ArunTeltia** [comment]
Not gonna lie it is looking cool but we are thinking of migrating the whole website to a theme based ui to make it aesthetically pleasing for users to surf on(You can have a look at the Ui theme in the readme )

And @FireQueen-3010 is already working on changing the color theme 
here is the PR she requested #146
If you want to work on something, can you work on the download page and stats page
We want the navbar in those to be changed by the navbar present in the home page 
Here is the issue that i just created for you https://github.com/ProjectSakura/ProjectSakura.github.io/issues/149
If you want to work on it message me on the issue i will assign the issue to you :)

Thank you for the contribution to project sakura

**Comment by LordShenron** [comment]
I think we should merge both issues here.

**Comment by ArunTeltia** [comment]
The issue is only redesigning the button, I guess Lets wait for @FireQueen-3010 Pull request to merge we will then came back to this issue

**Comment by LordShenron** [comment]
Now, its so much better @ArunTeltia

**Comment by ArunTeltia** [comment]
AHA YES

**Comment by dcs-soni** [comment]
So basically the navbar on the home page looks perfectly fine? And we want the same navbar in the Stats page that is present on the Blog page (but with similar design as that of Home page)? 

Correct me if I am wrong or please throw some ideas.

**Comment by LordShenron** [comment]
> So basically the navbar on the home page looks perfectly fine? And we want the same navbar in the Stats page that is present on the Blog page (but with similar design as that of Home page)?
> 
> Correct me if I am wrong or please throw some ideas.

Yes the navbar preview you showed in the video looks perfectly good and you can go ahead to do the same on download page and blog page. There is no navbar on stats and it don't need one.

**Comment by dcs-soni** [comment]
Cool! Thank you.
