### ISSUE TITLE
Redesigning navbar in stats and home page to the home page navbar

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#149]

**Comment by dcs-soni** [comment]
As suggested by you in #148 I want to work on this issue.

**Comment by ArunTeltia** [comment]
Great @dcs-soni assigning you this issue 🎉

**Comment by LordShenron** [comment]
You really don't need to create new issues for doing the same thing. There is literally a button on github to edit topics ;____;

**Comment by ArunTeltia** [comment]
Yeah this is the issue to create the navbar in download and stats page

**Comment by LordShenron** [comment]
I am closing it.
