### ISSUE TITLE
Remove Logs from the console in website 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#150]

**Comment by cryptofox17** [comment]
I'm assuming it means to remove all the console.log() statements from the files. If that's what you mean, then I can do that. Please assign this issue to me

**Comment by NehaK745** [comment]
@ArunTeltia can you assign this issue to me?

**Comment by ArunTeltia** [comment]
Yes @cryptofox17 I am assigning this to you as you commented first, 
Sorry @NehaK745, but if you want an issue I can assign you another one

**Comment by cryptofox17** [comment]
@ArunTeltia do you mean removing even the console.log(e) statements?
