### ISSUE TITLE
Refactoring buttons on the Blog Page.

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/ProjectSakura.github.io#157]
Refactoring buttons on blog page following the UI present in the readme file.

**Comment by FireQueen-3010** [comment]
Please assign me this as part of gssoc'21

**Comment by rhythmjayee** [comment]
> Please assign me this as part of gssoc'21

sure

**Comment by FireQueen-3010** [comment]
Ok tnx :)
