### ISSUE TITLE
Redesiging the modal on download page

### ISSUE THREAD

**Issue by LordShenron** [ProjectSakura/ProjectSakura.github.io#158]
The current modal that appears on clicking on changelog button is not very good.

**Comment by FireQueen-3010** [comment]
I can do this, please assign me this.

**Comment by ArunTeltia** [comment]
@LordShenron Level 4 issue is not a valid issue according to gssoc level3 is the biggest issue, i am changing the name of level4 to urgent

**Comment by LordShenron** [comment]
> @LordShenron Level 4 issue is not a valid issue according to gssoc level3 is the biggest issue, i am changing the name of level4 to urgent

Lmao brah.. very nice and quick of you after tagging so many lvl 4

**Comment by ArunTeltia** [comment]
I changed @LordShenron every single one of them 😂

**Comment by FireQueen-3010** [comment]
I admit that I was initially overjoyed looking at the level 4 tag.😛. Besides, thanks for assigning me this ! @ArunTeltia @LordShenron @rhythmjayee :)

**Comment by LordShenron** [comment]
> I changed @LordShenron every single one of them joy

Thanks my slave :P 

> I admit that I was initially overjoyed looking at the level 4 tag.stuck_out_tongue. Besides, thanks for assigning me this ! @ArunTeltia @LordShenron @rhythmjayee :)
I was more excited giving out level 4 issues xD

**Comment by ArunTeltia** [comment]
Thanks my slave :P

I don't condone this behavior 😂 🤦‍♀️
