### ISSUE TITLE
[Bug] Hovering the mouse over blog page heading doesn't work on every heading 

### ISSUE THREAD

**Issue by yasharth291** [ProjectSakura/ProjectSakura.github.io#161]
I was trying to hover over the headings but the behavior of every heading was different from one another.

**Comment by ArunTeltia** [comment]
Which Browser you are using @yasharth291, working fine for windows10 and microsoft edge

**Comment by yasharth291** [comment]
Chrome

**Comment by dcs-soni** [comment]
I checked in Chrome and it's working fine. Exactly on which heading you saw that issue?

**Comment by ArunTeltia** [comment]
Me too I checked it and its working fine can you share screenshot

**Comment by yasharth291** [comment]
yeah i will share video

**Comment by ArunTeltia** [comment]
Any updates @yasharth291 ?
