### ISSUE TITLE
Website fails many validation checks and generates many errors

### ISSUE THREAD

**Issue by dcs-soni** [ProjectSakura/ProjectSakura.github.io#171]
The HTML code in the website is broken at some points and due to which it does not pass validation checks. Some errors need to be looked at while other small errors can be ignored for some time. 

Below is the screenshot of the type of errors that I can resolve. I'll try to remove almost all the errors but the warnings are also generated that too in a big chunk. Need ample time to solve those. 
![image](https://user-images.githubusercontent.com/52232900/111449133-1cbb8580-8735-11eb-99ed-f86b15c6b20b.png)

**Comment by dcs-soni** [comment]
Please assign this to me and please add the required labels too.

**Comment by ArunTeltia** [comment]
Yes these are valid issues i am assigning it to you @dcs-soni

**Comment by ArunTeltia** [comment]
@dcs-soni are you working on this if yes, I will suggest you to create smaller PRs, because eventually this is a big issue

**Comment by dcs-soni** [comment]
Yep. Working on it. Smaller PRs as in which sense? Less number of PRs?

**Comment by ArunTeltia** [comment]
Means high amount of pr with less line of code change such that it is easy to review

**Comment by dcs-soni** [comment]
Sure. Will take care of it.
