### ISSUE TITLE
UI : Adding a navbar to the stats page

### ISSUE THREAD

**Issue by tanishq-arya** [ProjectSakura/ProjectSakura.github.io#173]
### Describe the problem that you'd like solved
Adding navbar to the Stats UI page

**Comment by ArunTeltia** [comment]
Yes Definitely we need it 
Points to be noted: Add a navbar that is present in the homepage.
If you want to work, I can assign it to you

**Comment by tanishq-arya** [comment]
Yes I am interested. One question. Should I match the theme or not ?

**Comment by ArunTeltia** [comment]
Just check the homepage navbar jou have to make a navbar look like that

**Comment by tanishq-arya** [comment]
Okay

**Comment by kanishkaa24** [comment]
Hello! Can i work on this ?

**Comment by ArunTeltia** [comment]
Lets wait for 6 hours ,@tanishq-arya are you working on this ?
If you want to work on a issue @kanishkaa24 do you want to work on the contributors page 
@LordShenron Its time we should add a contributors page what you think ?
 
 Ping me on discord if you want to work on something @kanishkaa24 , will assign you a good first issue

**Comment by kanishkaa24** [comment]
> Lets wait for 6 hours ,@tanishq-arya are you working on this ?
> If you want to work on a issue @kanishkaa24 do you want to work on the contributors page
> @LordShenron Its time we should add a contributors page what you think ?
> 
> Ping me on discord if you want to work on something @kanishkaa24 , will assign you a good first issue

Would love to work on the contributors page.

**Comment by tanishq-arya** [comment]
@AdityaTeltia not right now, something came up. You can assign to someone else if you want.

**Comment by AdityaTeltia** [comment]
> @AdityaTeltia not right now, something came up. You can assign to someone else if you want.

Why you tagged me ?

**Comment by ArunTeltia** [comment]
Okay @DevrajDC, Is working on the whole navbar, Assigning this issue to you devraj, and you accidentally tagged my brother HAHA

**Comment by DevrajDC** [comment]
Assign this issue to me🤟
I am working on navbar

**Comment by tanishq-arya** [comment]
> > @AdityaTeltia not right now, something came up. You can assign to someone else if you want.
> 
> Why you tagged me ?

Sorry for the inconvenience. Did it by mistake.

**Comment by gaulghost** [comment]
Can I work on this also? @ArunTeltia

**Comment by ArunTeltia** [comment]
@tanishq-arya is there any progress

**Comment by tanishq-arya** [comment]
@ArunTeltia Sorry I had my exams so I wasn't able to work on this.

**Comment by ArunTeltia** [comment]
NO problem tanishq focus on your exam, I dont think anyone will be interested in this one please start working on sunday 🙌
I am just trying to close issues as many as i can so that we can move ahead HAHA

**Comment by LordShenron** [comment]
Closing this for now.
