### ISSUE TITLE
update readme contributors to show contributors profile image in readme itself

### ISSUE THREAD

**Issue by rajeshpanjiyar** [ProjectSakura/ProjectSakura.github.io#175]
I want to add the **contributor's** section in the readme file. It is one of the best parts of every readme.
- I am a *participant* in **GSSoC'21**
- I would like to be assigned and start working.

**Comment by ArunTeltia** [comment]
Actually we are thinking of creating a separate page in our website for all the esteemed contributors, If you want to work on creating that you can get this issue, and please be careful with the issue type its not a bug its more of a questions :)
