### ISSUE TITLE
Changing the font and color in stats page

### ISSUE THREAD

**Issue by cryptofox17** [ProjectSakura/ProjectSakura.github.io#177]
### Describe the problem that you'd like solved

Not a major problem but the stats page has a completely different color scheme from the rest of the website. It uses a light theme whereas every other page uses a consistent dark background. Even the font family used isn't Poppins which is the recommended one in the style guide. 

### Proposal & Constraints

I want to work and make the page look a bit more consistent without affecting the current layout.

**Comment by ArunTeltia** [comment]
@LordShenron should we add a switch button for switching css from dark to white

**Comment by ArunTeltia** [comment]
Assigning you definitely need a dark theme, Let me know if you stuck somewhere

**Comment by LordShenron** [comment]
> @LordShenron should we add a switch button for switching css from dark to white

totally yes!
