### ISSUE TITLE
Redesigning Navbar on Homepage and Fixing Issues caused by previous Navbar

### ISSUE THREAD

**Issue by DevrajDC** [ProjectSakura/ProjectSakura.github.io#179]
Navbar needs to be fixed since it is affecting the webpage width. I will redesign the whole Navbar with respect to our theme and add smooth animations. Also the user experience would increase in the New design.

Image of the issue caused by previous navbar:
![image](https://user-images.githubusercontent.com/65373279/111754060-91213080-88bd-11eb-8390-36b6e3cc66ef.png)

**Comment by ArunTeltia** [comment]
For now we will hold on the navbar issues, @LordShenron He will be designing the navbar for all the pages,

**Comment by LordShenron** [comment]
> For now we will hold on the navbar issues, @LordShenron He will be designing the navbar for all the pages,

I was going to open an issue about this xD..

**Comment by ArunTeltia** [comment]
🤣🤣sure

**Comment by ArunTeltia** [comment]
Resolved Now we have new issues, closing for now
