### ISSUE TITLE
Remove Internal CSS

### ISSUE THREAD

**Issue by kanishkaa24** [ProjectSakura/ProjectSakura.github.io#180]
In this issue, I will remove the internal CSS and add it to the CSS files. Please assign this under GSSOC.

**Comment by ArunTeltia** [comment]
Sub Part of #116 go for it tagging the parent issue for some clear understanding @kanishkaa24

**Comment by Kavs-123** [comment]
Hey @ArunTeltia, can I work on this issue?
If it is not solved by @kanishkaa24 ??

**Comment by ArunTeltia** [comment]
Yes Go for it @Kavs-123 I talked to her she is having health issues you can work on it🎉

**Comment by Kavs-123** [comment]
> Yes Go for it @Kavs-123 I talked to her she is having health issues you can work on it🎉

Ohk @ArunTeltia Thank you !!

**Comment by ArunTeltia** [comment]
Please let me know if you understand the concept of this issue @Kavs-123

**Comment by Kavs-123** [comment]
> Please let me know if you understand the concept of this issue @Kavs-123

Sure sure I will!

**Comment by arpit456jain** [comment]
@Kavs-123 are you working on this issue . 
@ArunTeltia can i work ont this issue

**Comment by Kavs-123** [comment]
> @Kavs-123 are you working on this issue .
> @ArunTeltia can i work ont this issue

@arpit456jain  
Yes, I am working on this issue!

**Comment by ArunTeltia** [comment]
Part of #116

**Comment by ArunTeltia** [comment]
Still many files have issues, thats why I am reopening it

**Comment by RahulBansal0502** [comment]
I can work on this issue @ArunTeltia @LordShenron

**Comment by LordShenron** [comment]
> Still many files have issues, thats why I am reopening it

I am closing this because we should do this ourself. It's a sensitive issue.
