### ISSUE TITLE
Order CSS in alphabetical order

### ISSUE THREAD

**Issue by kanishkaa24** [ProjectSakura/ProjectSakura.github.io#181]
In this issue, I'll be alphabetically ordering CSS elements. Please assign under GSSOC.

**Comment by ArunTeltia** [comment]
Yeah Assigning you the issue @kanishkaa24

**Comment by vedikaag99** [comment]
@ArunTeltia can I take up this issue if it's open to grab? I'm a GSSOC participant.

**Comment by ArunTeltia** [comment]
This is complex @vedikaag99 because our website is a mess, if you want to work on it i would be more than happy to assign you this
Let me know if you get stuck somewhere
Assigning you
