### ISSUE TITLE
Updating the screenshots section in readme

### ISSUE THREAD

**Issue by cryptofox17** [ProjectSakura/ProjectSakura.github.io#183]
### Describe the problem that you'd like solved

Since there has been a lot of UI changes in the website, the screenshots in the readme file (stats, blogs) are irrelevant. 

### Proposal & Constraints

They could be updated by adding new screenshots, but adding a gif might be a better option as that would occupy lesser space and can include every page. 

### Additional context

Please assign this issue to me.

**Comment by ArunTeltia** [comment]
Yeah Go for it @cryptofox17
