### ISSUE TITLE
Create a sign up form for new users . 

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/ProjectSakura.github.io#185]
### Describe the problem that you'd like solved
A sign up form for new users who are interested in the project might be good to send them updates or newsletters.

### Proposal & Constraints
Creating a sign up form and displaying the option in the nav bar of home page.

On clicking the button, a pop-up should appear for the user to fill in details and these details should be stored in a database (like mongodb) and sending these updates should be automated.

### Additional context
Along with custom form, third party authentication like google can also be enabled.

The custom form can be divided into frontend and backend parts again .

**Comment by FireQueen-3010** [comment]
Please assign me this as part of gssoc'21

**Comment by ArunTeltia** [comment]
It will require a backend and a server and not gonna lie there are no use for sign ups in the project, If you have anything in mind that can attract audience will love to hear about that, 
For now i dont think we might need this, what's your thought @LordShenron

**Comment by LordShenron** [comment]
It's invalid for us.. So, closing it.
