### ISSUE TITLE
Adding some changes in the download.html page

### ISSUE THREAD

**Issue by cryptofox17** [ProjectSakura/ProjectSakura.github.io#195]
### Describe the problem that you'd like solved

Making some enhancements to downloads page

### Proposal & Constraints

 - Add padding to the modal, the text currently sticks to the border of the modal.
 - Change the modal text font to Poppins as per the style guide
- Making the search input field left aligned
- The close btn looks fine on desktop and large screen but looks squished on mobile screen, its CSS could be modified 
- Way too many comments in the CSS which could be removed

### Additional context

I would like to work on this issue

**Comment by ArunTeltia** [comment]
Looks good to me @cryptofox17 🙌, Assigning You the issue
