### ISSUE TITLE
Adding footer hover effects in all pages.

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/ProjectSakura.github.io#198]
The footer links don't have any hover or click effects.

**Comment by FireQueen-3010** [comment]
Please assign me this under gssoc'21

**Comment by ArunTeltia** [comment]
Is this footer for the home page ?

**Comment by FireQueen-3010** [comment]
For both home page and downloads pages, do I make separate prs for both? @ArunTeltia
