### ISSUE TITLE
Move to top button 

### ISSUE THREAD

**Issue by arpit456jain** [ProjectSakura/ProjectSakura.github.io#199]
I am always frustrated when I have to scroll the page back to top every time.
There should be a back to top button with smooth scrolling.

### Proposal & Constraints

I can try to add this feature.

**Comment by ArunTeltia** [comment]
Go for it @arpit456jain please follow the ui theme in readme tho

**Comment by arpit456jain** [comment]
ok @ArunTeltia ca you please assign it to me.

**Comment by arpit456jain** [comment]
@ArunTeltia kindly assign it to me and review my PR.
And I am a Gssoc'21 participant so please add label of gssoc on PR
