### ISSUE TITLE
Light Mode with Toggle button

### ISSUE THREAD

**Issue by arpit456jain** [ProjectSakura/ProjectSakura.github.io#200]
I want to add light mode to it with a toggle button so user can choose theme  according to its choice.
I am a Gssoc'21 participant Kindly assign it to me.

**Comment by ArunTeltia** [comment]
In which page you want to make a light theme ?

**Comment by arpit456jain** [comment]
@ArunTeltia in project's main page. If you like i will add it to others also .
@ArunTeltia but firstly kindly assign me this issue and issue. #199 

You allowed me to work on that issue and i had created a PR but i am not assigned please assign me before merging

**Comment by ArunTeltia** [comment]
Assigned that issue to you @arpit456jain , yes we can switch to light theme but there is no need for it, @LordShenron  whats your thought on this, according to me this is not important for us right now 

@arpit456jain If you want to work on something you can message me on discord or here and we will figure out one of the frontend project you can exclusively work on

**Comment by arpit456jain** [comment]
Ok @ArunTeltia   sure.

**Comment by LordShenron** [comment]
Invalid.
