### ISSUE TITLE
Add hover effects to Contact Us  cards.

### ISSUE THREAD

**Issue by padmajabhol** [ProjectSakura/ProjectSakura.github.io#202]

**Comment by ArunTeltia** [comment]
Can you please elaborate the issue

**Comment by padmajabhol** [comment]
> Can you please elaborate the issue

![Screenshot (84)](https://user-images.githubusercontent.com/75530516/112830591-62227000-90b0-11eb-983a-a5eed054e051.png)
I want to change the hover effect in this particular section.

**Comment by ArunTeltia** [comment]
okay go for it @padmajabhol

**Comment by ArunTeltia** [comment]
I dont think we require anything fancy after the board meeting we have for that reason i am closing this issue if you have worked on it @padmajabhol please reopen the issue and create a pr will figure something out
