### ISSUE TITLE
Download Page Unsupported Details 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/ProjectSakura.github.io#205]
Hello All the contributors,

So we are working on download page and we are trying to make the current download page unsupported, it does not mean the page will disappear it simply means we are trying to make a new download page from the scratch. So we are currently not accepting any issues and PR's related to download page, If you want to contribute and stuck somewhere message me in this thread or on discord we will sort some issues for you where you can challenge your skills 

Tagging the main collaborators of this repository

@cryptofox17 @FireQueen-3010 @LordShenron @DevrajDC @tanishq-arya @yasharth291 @rhythmjayee @arpit456jain @kanishkaa24 @gaulghost

Let me know if you are blocked somewhere, or not have issues to work on, I will try to help you as soon as I can 

Open Source For the win 🎉✨

**Comment by cryptofox17** [comment]
I'd like to work any frontend related issue here. As of now I can't find any issues with the website but if you have any please let me know

**Comment by ArunTeltia** [comment]
@cryptofox17 messaged you on discord

**Comment by tanishq-arya** [comment]
> I'd like to work any frontend related issue here. As of now I can't find any issues with the website but if you have any please let me know

+1

**Comment by FireQueen-3010** [comment]
> I'd like to work any frontend related issue here. As of now I can't find any issues with the website but if you have any please let me know

+1

**Comment by LordShenron** [comment]
Wew

**Comment by ArunTeltia** [comment]
> Even I would like to
@FireQueen-3010 Lets focus on wiki-redesign you are doing amazing work there 🙌

**Comment by FireQueen-3010** [comment]
> > Even I would like to
> 
> @FireQueen-3010 Lets focus on wiki-redesign you are doing amazing work there 🙌

Yeah okay :)

**Comment by LordShenron** [comment]
Well I redesigned the new download page.. So, now contributors can work on it.
