### ISSUE TITLE
Validate HTML

### ISSUE THREAD

**Issue by tanishq-arya** [ProjectSakura/ProjectSakura.github.io#208]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/77333275/112987597-86e61880-9180-11eb-9138-c082ae2cd7d7.png)

### Steps to Reproduce

1. check here https://validator.w3.org/nu/?doc=https%3A%2F%2Fprojectsakura.xyz%2F

* Actual: 
* Expected: 

### Details

- **Browser type/version?** 
- **Operating system?**

**Comment by ArunTeltia** [comment]
Definately one of the most important thing for the SEO point of view adding some tags to show the importance of the issue, Thankyou for creating this issue @tanishq-arya , assigning the issue to you if thats okay with you

**Comment by ArunTeltia** [comment]
@cryptofox17 @FireQueen-3010 want to work on it along with @tanishq-arya this is something that is really important and its really time consuming to do you can assign different page for the HTML validations

**Comment by tanishq-arya** [comment]
I was thinking of starting from the index.html page.

**Comment by cryptofox17** [comment]
@ArunTeltia ok, then I could work on stats.html page, if that's ok with with @tanishq-arya

**Comment by ArunTeltia** [comment]
@cryptofox17 go for stats and blog page

**Comment by tanishq-arya** [comment]
Can I make a new class for the center tag removal ? I am thinking of display flex and centering it.

**Comment by ArunTeltia** [comment]
If you think that will be a wise choice do it will figure some best practice once you create a pull request 
for now go for it

**Comment by FireQueen-3010** [comment]
> @cryptofox17 @FireQueen-3010 want to work on it along with @tanishq-arya this is something that is really important and its really time consuming to do you can assign different page for the HTML validations

I would like to work on the blog page if thats okay

**Comment by rhythmjayee** [comment]
i reopened it beause it has still work to do

**Comment by ArunTeltia** [comment]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fprojectsakura.xyz%2F
@tanishq-arya wanna look at this as well

**Comment by tanishq-arya** [comment]
I was about to talk to you about this. I tried changing the h1 headings to h2 then the heading styles change. So how should I proceed with this ?

**Comment by ArunTeltia** [comment]
Okay these are not the SEO Level issues @tanishq-arya lets just leave this for the time being we will work on it later

**Comment by ArunTeltia** [comment]
Is there any page that is remaining, if someone can inform that will be great otherwise will close this issue

**Comment by tanishq-arya** [comment]
Downloads page. 
https://validator.w3.org/nu/?doc=https%3A%2F%2Fprojectsakura.xyz%2Fdownload.html
There are not many errors I'll try to make a PR by today.

**Comment by ArunTeltia** [comment]
Yes That would be great @tanishq-arya lets just finish all the issues and work on something else, If you have any idea on react 
Do you want to work on contributors section @tanishq-arya

**Comment by tanishq-arya** [comment]
> Yes That would be great @tanishq-arya lets just finish all the issues and work on something else, If you have any idea on react
> Do you want to work on contributors section @tanishq-arya

Sure. I just started with React so I was thinking to get a grip on basics in 1-2 days then I can start working on the contributors section.

**Comment by ArunTeltia** [comment]
Great so our main task would be to build contributors and wiki section 
@vedikaag99 and @FireQueen-3010 are working on the contributors section 
I will also start working on it

**Comment by ArunTeltia** [comment]
HOPE THIS IS CLOSED FOR GOOD
