### ISSUE TITLE
Adding Hover effect for the cards in get sakura! section

### ISSUE THREAD

**Issue by Avishake007** [ProjectSakura/ProjectSakura.github.io#214]
I want to add hovering effect for the cards in get sakura! section
please assign me for this task under gssoc'21

**Comment by ArunTeltia** [comment]
I dont know whether it will look great or not, 
@LordShenron should he work on it

**Comment by LordShenron** [comment]
> I dont know whether it will look great or not,
> @LordShenron should he work on it

We need to rework the guidelines

**Comment by ArunTeltia** [comment]
Please work on it @LordShenron

**Comment by ArunTeltia** [comment]
I dont think we need this after discussion @LordShenron 
We dont want any more fancy work on the page 
Closing it for that reason
