### ISSUE TITLE
Adding transitions to sudden hover effects on buttons

### ISSUE THREAD

**Issue by N-Shar-ma** [ProjectSakura/ProjectSakura.github.io#222]
## Problem
All the links in the navbar have a hover state but it appears immediately and not gradually which looks slightly jarring. The buttons in get Sakura and Contact Us sections also have the same issue where they have instant hover effects instead of transitioning slowly to them

## Proposed Solution
- I'd like to add a transition to all these buttons for better UX. After experimenting, in the browser dev tools, I realise 300ms is a good duration for them. 
- Additionally, for the navbar links, I'd like to convert the instant underline on hover effect, to show the underline start as a dot at the center and gradually fill up till the left and right edges over 300ms. This would look much more appealing

I would love to solve this issue under GSSoC'21 @ArunTeltia

**Comment by ArunTeltia** [comment]
Sounds Good To me, 
@LordShenron should we accept this issue

**Comment by LordShenron** [comment]
Looks good..  just don't do it on download page.
