### ISSUE TITLE
Align Navbar

### ISSUE THREAD

**Issue by RahulBansal0502** [ProjectSakura/ProjectSakura.github.io#224]
Navbar alignment is not perfect it must be in right then it will look good. Also, I want to add a home option in Navbar as it is weird to click on the logo icon for home. I want to work on this issue as a GSSOC participant, please assign it to me @ArunTeltia

**Comment by ArunTeltia** [comment]
Yup definitely need to work on it go for it @RahulBansal0502 
Let me know if you get blocked somewhere or need help

**Comment by RahulBansal0502** [comment]
Thanks I will let you know.
