### ISSUE TITLE
Revamp Contact us page

### ISSUE THREAD

**Issue by RahulBansal0502** [ProjectSakura/ProjectSakura.github.io#225]
I want to revamp the contact us page like the below image:
![image](https://user-images.githubusercontent.com/56486309/113841854-c7ace580-97af-11eb-937d-9ee8954baad0.png)

If there is any issue in this regarding color we can make the required changes for that purpose. If you like my proposal please assign it to me. I am a GSSOC participant. @ArunTeltia @rhythmjayee @yasharth291

**Comment by ArunTeltia** [comment]
Really looks good but we don't need a contact form 
And contact form would eventually need a lambda function to store data in the database , and right now we cant afford a backend 

So thank you for your hard work in this , but sorry we can't add this to our page

Let me know if you need some issue to work on we will work something out 🙌

**Comment by RahulBansal0502** [comment]
Actually we can make contact form using formspree. So in this case we do not require any backend. Benifits of formspree:
1. No backend required 
2. Easy to connect
3. If someone has filled the form query send to the owner via mail.

**Comment by ArunTeltia** [comment]
What are you going to use for mail service? MailChimp?

@LordShenron do we need it ? I dont think we need it

**Comment by RahulBansal0502** [comment]
Formspree https://formspree.io/

**Comment by ArunTeltia** [comment]
Message me @ discord @RahulBansal0502, will tell you the problem related to it 
Never the less this looks really nyc, 

Here my discord ArunTeltia#4154

**Comment by LordShenron** [comment]
> I want to revamp the contact us page like the below image:
> ![image](https://user-images.githubusercontent.com/56486309/113841854-c7ace580-97af-11eb-937d-9ee8954baad0.png)
> 
> If there is any issue in this regarding color we can make the required changes for that purpose. If you like my proposal please assign it to me. I am a GSSOC participant. @ArunTeltia @rhythmjayee @yasharth291

Gonna sound harsh but we seriously don't need a contact form of any kind.
