### ISSUE TITLE
Footbar of stats page

### ISSUE THREAD

**Issue by smriti1313** [ProjectSakura/ProjectSakura.github.io#230]
Firstly, project sakura is just kawaiiiii :)

After checking your website and the linked pages I did find that the footer of sakura blog and sakura stats are different. Ain't wanna open an issue just for the sake to create an issue but i guess since this project is so cool there has to be some uniformity in it.

### Describe the problem that you'd like solved
I would like to alter the footer of sakura [stats](https://projectsakura.xyz/stats.html) and make it like sakura [blog](https://projectsakura.xyz/blog.html).

I would like to work on this issue under GSSOC'21.
Thank you

**Comment by ArunTeltia** [comment]
Thank You @smriti1313 for the king words, we know this is a defect in the website(This is affecting the Ui by a lot )
The thing about the footer is we are focusing on deleting the download.html(basically we will redirect all the traffic from that page to https://projectsakura.xyz/download )
SO changing anything in the download page would eventually be something that will not be there after 15-20 days 

and for home page stats page 
I think we can really work on the footer of the stats page that footer looks really dirty we can simply add a line to the website as it is in home page, If you want to work on it please let me know I can assign that to you :)

**Comment by ArunTeltia** [comment]
![uyfuiuypi](https://user-images.githubusercontent.com/43555219/114047721-87309300-98a7-11eb-9ce8-d70c8804f3cb.PNG)
here is the footer that can be used in the stats page 
also this Pr will be merged after the navbar is created by tanishq(he is currently working on the navbar for stats page)

**Comment by smriti1313** [comment]
> Thank You @smriti1313 for the kind words, we know this is a defect in the website(This is affecting the Ui by a lot )
> The thing about the footer is we are focusing on deleting the download.html(basically we will redirect all the traffic from that page to https://projectsakura.xyz/download )
> SO changing anything in the download page would eventually be something that will not be there after 15-20 days
> 
> and for home page stats page
> I think we can really work on the footer of the stats page that footer looks really dirty we can simply add a line to the website as it is in home page, If you want to work on it please let me know I can assign that to you :)

Yeah. i would def like to work on this☀️🙌🏽

**Comment by smriti1313** [comment]
> ![uyfuiuypi](https://user-images.githubusercontent.com/43555219/114047721-87309300-98a7-11eb-9ce8-d70c8804f3cb.PNG)
> here is the footer that can be used in the stats page
> also this Pr will be merged after the navbar is created by tanishq(he is currently working on the navbar for stats page)

Do you have any idea regarding how long will it take?

**Comment by ArunTeltia** [comment]
It actually depends on you @smriti1313 its fairly easy tho If you have any issues then let me know we can work on it

**Comment by smriti1313** [comment]
> 
> 
> It actually depends on you @smriti1313 its fairly easy tho If you have any issues then let me know we can work on it

No. I actually meant that how long will it take for tanishq to do? Because I guess that i will only be able to start my work after he's done.

**Comment by ArunTeltia** [comment]
Oho dont worry about it @smriti1313 this PR will eventually get merged for now work on this PR, He will be resolving the issue by 2 days i think, if he dont get blocked by something

**Comment by ArunTeltia** [comment]
https://github.com/ProjectSakura/ProjectSakura.github.io/pull/252
@smriti1313 please have a look at this footer this is the footer we want in stats page
and please also let me know the progress

**Comment by LordShenron** [comment]
The footer on stats page looks fine enough. What's left to do on it? @ArunTeltia

**Comment by ArunTeltia** [comment]
Not Sure I though it would look good with the download.html footer for now i am closing the issue as the creator of this issue  has asked me that she is having trouble with the timing
