### ISSUE TITLE
Improvement In Download Stats Page

### ISSUE THREAD

**Issue by Ankit0225** [ProjectSakura/ProjectSakura.github.io#231]
## Include Correct Percentage and removing Decimal 
![wrong](https://user-images.githubusercontent.com/73462619/114053866-f3fa5c00-98ac-11eb-91d8-627adb28ad5d.png)

**Comment by Ankit0225** [comment]
Hey I would Like to work on this issue please assign it to me I am a GSSoC participant

**Comment by yasharth291** [comment]
go ahead @Ankit0225

**Comment by ArunTeltia** [comment]
I dont think removing decimal is something we want, and why do you think the percentage is wrong @Ankit0225

**Comment by Ankit0225** [comment]
It looks awkward sometimes round off better I am doing 19.5% not 19% better than three-digit decimal hope u understand

**Comment by ArunTeltia** [comment]
Maybe it is awkward @Ankit0225, but there are devices that only have 39 total download and its percentage is less than 0.05%
rounding that to 0 would be really bad I think, If you want an other issue we can work on some of the genuine issue in the website 

Let me know if you want to work on some issue🎉

**Comment by Ankit0225** [comment]
@ArunTeltia Yes I want to work on some Genuine issue

**Comment by ArunTeltia** [comment]
Okay right now i have been commenting via mobile will tell you some issue @Ankit0225 by tomorrow

**Comment by Ankit0225** [comment]
@ArunTeltia Should I continue to work on this issue Or should I leave because It is the first issue If you don't like the code I have edited you can reject

**Comment by ArunTeltia** [comment]
There is no need to work on this issue as this is not an issue on the first place sorry about that😅
will tell you some issue by tomorrow to work on it would be great if you can tell me your skills 
so that i can assign you an issue

**Comment by Ankit0225** [comment]
@ArunTeltia ok

**Comment by Ankit0225** [comment]
I am deleting this issue

**Comment by ArunTeltia** [comment]
yes close it
