### ISSUE TITLE
Bootstrapmade backlinks

### ISSUE THREAD

**Issue by vibhanshujainiiitr** [ProjectSakura/ProjectSakura.github.io#233]
When I was going through the complete code of the website, I found the backlinks of the BOOTSTRAPMADE which are still active. 
And the most horrible part is the footer credit is removed. 

This is highly dangerous, as the official authorities can anytime take legal action against this. 
Please provide the proper credit in the footer again, or the alternate and safer option is to remove all the backlinks. 

We very well know, how easy is it for them to come to our website using those backlinks.

**Comment by ArunTeltia** [comment]
wanna work on it ? @vibhanshujainiiitr

**Comment by vibhanshujainiiitr** [comment]
Yes, I can do that.

**Comment by vibhanshujainiiitr** [comment]
I updated that.
