### ISSUE TITLE
Revamp footer

### ISSUE THREAD

**Issue by RahulBansal0502** [ProjectSakura/ProjectSakura.github.io#236]
I want to revamp the footer of this website like the below image:
![image](https://user-images.githubusercontent.com/56486309/114192799-85c89e80-996b-11eb-8783-0cba02c1946f.png)
This is not an actual image required CSS will be applied to it like the black background but links will be available in the footer.
I am a GSSOC participant assign it to me @ArunTeltia @yasharth291

**Comment by yasharth291** [comment]
okay work on it @RahulBansal0502

**Comment by ArunTeltia** [comment]
Not sure if this is the type of footer we want, please have a look at download.html page 
that footer is what we want in the  stats page have a look at this PR https://github.com/ProjectSakura/ProjectSakura.github.io/pull/252
If you want to work on it please tell me

**Comment by RahulBansal0502** [comment]
Ok I will do that @ArunTeltia

**Comment by ArunTeltia** [comment]
So @RahulBansal0502 sorry to inform it to you but @LordShenron and I discussed and we came to conclusion that footer in all the pages looks good and we dont need any changes in it. Will award you level3 for the other Pr you did

**Comment by RahulBansal0502** [comment]
okay, then I will close this issue.
