### ISSUE TITLE
Height of navbar

### ISSUE THREAD

**Issue by satcasm** [ProjectSakura/ProjectSakura.github.io#238]
In smaller screens the height of the navbar seems a bit more that required. 
Would like to reduce it under GSSOC' 21.
Please assign this issue to me.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/114308474-cce89800-9b01-11eb-88d2-304f70ae91c9.png)

**Comment by LordShenron** [comment]
Nah not needed.
