### ISSUE TITLE
Adding hover effect to the brand name

### ISSUE THREAD

**Issue by satcasm** [ProjectSakura/ProjectSakura.github.io#239]
Would like to add some sort of hovering effect on the brand name. Not sure if it is required at all, but have seen it in some sites and it looks pretty good.
Please assign it to me if seemed necessary under GSSOC' 21.
Thanks!

**Comment by yasharth291** [comment]
hey @satcasm  can you please put some photos or video to show this bug

**Comment by satcasm** [comment]
@yasharth291 It's technically not a bug , just a proposal . Check this [out](https://codepen.io/caraujo/full/LVPzxO). I can make something like this on the brand name

**Comment by yasharth291** [comment]
okay i understood i am assigning you this just work on this and create a pr for the same good luck @satcasm

**Comment by satcasm** [comment]
@yasharth291 I have created a PR , have a look at it.
Thanks!
