### ISSUE TITLE
Adding a donation chart to take donations directly from websites

### ISSUE THREAD

**Issue by yasharth291** [ProjectSakura/ProjectSakura.github.io#240]
@AdityaTeltia @LordShenron  this is just a discussion please put your ideas on this

**Comment by RahulBansal0502** [comment]
I want to work on this issue @yasharth291 @ArunTeltia @LordShenron

**Comment by yasharth291** [comment]
this is just discussion not a issue yet

**Comment by RahulBansal0502** [comment]
Ohh okay

**Comment by yasharth291** [comment]
@LordShenron  @ArunTeltia

**Comment by LordShenron** [comment]
Not needed for us.
