### ISSUE TITLE
Alignment in Contact us page

### ISSUE THREAD

**Issue by RahulBansal0502** [ProjectSakura/ProjectSakura.github.io#244]
![image](https://user-images.githubusercontent.com/56486309/114406800-7349a180-9bc5-11eb-9123-160d59be0715.png)

If you see the above image properly then you find that the image of the mailbox is slightly below the card which is looking good but in the case of telegram and Twitter the icons touch the card boundary I want to work on this issue. @ArunTeltia @LordShenron @yasharth291

**Comment by yasharth291** [comment]
okay assigning you

**Comment by Rohan27s** [comment]
can i work on this issue?

**Comment by RahulBansal0502** [comment]
I am working on it @Rohan27s

**Comment by Rohan27s** [comment]
okhay
