### ISSUE TITLE
Make site responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [ProjectSakura/ProjectSakura.github.io#245]
I want to make site responsive : 

[GSSOC'21]

Some of the Screenshots:

![sak-1](https://user-images.githubusercontent.com/66208607/114517403-f289b480-9c5b-11eb-95d3-7fe8fd02a939.png)

![sak-2](https://user-images.githubusercontent.com/66208607/114517417-f3bae180-9c5b-11eb-8650-bdeaaf8a240e.png)
In the above image the second card i.e blog one is not aligned properly..

Please assign me this issue @yasharth291

**Comment by LordShenron** [comment]
The website is already responsive it's just few issues that don't need too deep workarounds. Also Contributors section is getting removed soon.

**Comment by Bhavya-Sehgal** [comment]
okay, but the download section and contact us section are also not aligned properly  . Can I fix that?
@LordShenron

**Comment by yasharth291** [comment]
ok go ahead
