### ISSUE TITLE
Improving the alignment in footer in download.html

### ISSUE THREAD

**Issue by cryptofox17** [ProjectSakura/ProjectSakura.github.io#246]
The footer looks fine in phone view but the alignment could be improved for larger screen. 
![Screenshot_20210413-172351442](https://user-images.githubusercontent.com/64403591/114548269-2cb77e00-9c7d-11eb-9504-d09c8a56615b.jpg)

### Describe the problem that you'd like solved
- the sponsor logo is much bigger than the website's logo 
- the description of prSakura could be right below the logo 
- Lineage OS typo
- the maintainers names could be a link to their GitHub repo

### Proposal & Constraints
Fixing the above mentioned issues 

### Additional context
I would like to work on this

**Comment by yasharth291** [comment]
okay go ahead
