### ISSUE TITLE
Bug in contact us and Get Sakura page

### ISSUE THREAD

**Issue by RahulBansal0502** [ProjectSakura/ProjectSakura.github.io#251]
![image](https://user-images.githubusercontent.com/56486309/114732049-d7a06880-9d5f-11eb-8ff7-28071f442360.png)
![image](https://user-images.githubusercontent.com/56486309/114732102-e0913a00-9d5f-11eb-86d9-566d59180130.png)
I have recently seen this bug on this website Please see this it's so urgent @ArunTeltia @LordShenron @yasharth291 Assign it to me.

**Comment by LordShenron** [comment]
Okay go ahead

**Comment by ArunTeltia** [comment]
YUP PRIORITY VERY HIGH FOR THIS ONE

**Comment by ArunTeltia** [comment]
#258 after merge i am still having issues in my laptop can you check @RahulBansal0502

**Comment by LordShenron** [comment]
> #258 after merge i am still having issues in my laptop can you check @RahulBansal0502

Try in incognito

**Comment by RahulBansal0502** [comment]
![image](https://user-images.githubusercontent.com/56486309/115048906-bbcfca80-9ef7-11eb-88d6-c57731220dd8.png)
Can you please check this I think because of this that happens? @ArunTeltia

**Comment by ArunTeltia** [comment]
No it is actually happening on the main website @RahulBansal0502
