### ISSUE TITLE
Wanted to applied animation in Contact section and Download section

### ISSUE THREAD

**Issue by RahulBansal0502** [ProjectSakura/ProjectSakura.github.io#261]
Wanted to apply animation to the above-mentioned sections. If a user hovers over the cards the below effect will be shown 
![image](https://user-images.githubusercontent.com/56486309/115067655-da8d8b80-9f0e-11eb-9fa2-726d35a88213.png)
@ArunTeltia @LordShenron @yasharth291

**Comment by yasharth291** [comment]
assigning it to you

**Comment by LordShenron** [comment]
It's invalid. @yasharth291 don't just allow anything without asking me or Arun.
