### ISSUE TITLE
Some device maintainers names re hidden behind scroll bar 

### ISSUE THREAD

**Issue by shonali2600** [ProjectSakura/ProjectSakura.github.io#264]
### Evidence / Screenshot (if possible)

![sakura](https://user-images.githubusercontent.com/57946528/115136138-63094a80-a03b-11eb-8f35-4f989ef4895e.png)

* Actual: There are so many device maintainers in the same row
* Expected: Some of the maintainers can be put in another row.

### Details

- **Browser type/version?**  Opera
- **Operating system?** Windows10

**Comment by shonali2600** [comment]
Please assign it to me i would like to work on this

**Comment by ArunTeltia** [comment]
https://github.com/ProjectSakura/ProjectSakura.github.io/issues/265#issuecomment-821950030
refer this comment @shonali2600 :), this section will be deleted in 4-5 days tops
