### ISSUE TITLE
All the contributors haven't been added to the site.

### ISSUE THREAD

**Issue by shonali2600** [ProjectSakura/ProjectSakura.github.io#265]
There are only 3 contributor listed there, but total contributor are 19, I would like to add all of them, please try to assign me this

**Comment by ArunTeltia** [comment]
Actually @shonali2600 we are creating the contributors section specially for our precious contributors there are many contributors that i have in mind that must be on that section(@vedikaag99  @RahulBansal0502) they are working effortlessly for us, if you have a little idea of react you can contribute to us on that website we will love to have your contribution there 

Please close this issue after reading :)

**Comment by ArunTeltia** [comment]
https://github.com/ProjectSakura/contributors
here is the repo link if you wanna check
