### ISSUE TITLE
Update README with setup and contributing guidelines

### ISSUE THREAD

**Issue by Samridhi-98** [ProjectSakura/ProjectSakura.github.io#266]
### Describe the problem that you'd like solved
README needs to be updated with the proper setup and contributing guidelines of the project.

### Proposal & Constraints

- [ ] Add project `setup` section in the `Readme.md`.
- [ ] Add `contribution.md` in the `Readme.md`.
- [ ] Enhance the UI also lil bit

**Comment by Samridhi-98** [comment]
@ArunTeltia  @LordShenron  I would like to work on it will you please assign it to me.

**Comment by ArunTeltia** [comment]
I am not sure this is a big concern for us right now if you want, you can work on react projects which I can help you get started with 

If you are interested ping me on the discord we can have a look on the issue for you :)

**Comment by Samridhi-98** [comment]
> I am not sure this is a big concern for us right now if you want, you can work on react projects which I can help you get started with
> 
> If you are interested ping me on the discord we can have a look on the issue for you :)

Will you please provide me the link of react the project?

**Comment by ArunTeltia** [comment]
Closing this issue after we have meeting
