### ISSUE TITLE
Uniformity with the footer in stats 

### ISSUE THREAD

**Issue by LordShenron** [ProjectSakura/ProjectSakura.github.io#270]
The footer in our landing and download page are very different. We want to design the footer in our landing page similar to the download page.

**Comment by cryptofox17** [comment]
Could I work on this?

**Comment by ArunTeltia** [comment]
Yes @cryptofox17 assigned to you, Thank You

**Comment by ArunTeltia** [comment]
Lets just do this for stats as well, we don't need this for blog this will make our whole website uniform
