### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [ProjectSakura/ProjectSakura.github.io#278]
I want to add dark mode to website

Please assign me this issue @yasharth291 @LordShenron

**Comment by LordShenron** [comment]
Where? 😂 It's all dark already

**Comment by Bhavya-Sehgal** [comment]
So I will make it light then😂
Switch between dark n light will be good. 
@LordShenron

**Comment by LordShenron** [comment]
> So I will make it light thenjoy
> Switch between dark n light will be good.
> @LordShenron

I am not sure if that is what we want to do.. coz we have some pages written in javascript and they are all in dark mode. So, if you make some pages switch to light mode they will look odd.

**Comment by Bhavya-Sehgal** [comment]
Okay!
