### ISSUE TITLE
Scroll Top arrow

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [ProjectSakura/ProjectSakura.github.io#279]
I want to add scroll-top arrow to website that will allow the user to directly reach at the top of the page.

[GSSOC'21]

Please assign me this issue @LordShenron @yasharth291

**Comment by ArunTeltia** [comment]
Go For it @Bhavya-Sehgal assigning this one to you

**Comment by ArunTeltia** [comment]
Closed by #283 , Thank you for contributing to project sakura @Bhavya-Sehgal
