### ISSUE TITLE
Hover effect in feature and team section

### ISSUE THREAD

**Issue by RuchiGitHu** [ProjectSakura/ProjectSakura.github.io#282]
### Describe the problem that you'd like solved

I want to add Hover effect in feature section as well as team section so that the content of these sections will give good user experience as well as will look attractive and more readable.
### Proposal & Constraints

I will use coloured hover effect so that the website looks attractive and creative.

### Additional context

I can use 3D effect as well.

**Comment by RuchiGitHu** [comment]
Please assign this issue to me under gssoc21..
Looking forward to contribute here....

**Comment by LordShenron** [comment]
@RuchiGitHu meh

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu meh

Please let me what you said? I didn't understand....

**Comment by ArunTeltia** [comment]
@RuchiGitHu , we dont want to make our website fancy, we want to make it simple and straight, if you find any other bugs than you can report on it but right now this is not an actual issue for us
