### ISSUE TITLE
Sticky social media sidebar

### ISSUE THREAD

**Issue by gayatri517** [ProjectSakura/ProjectSakura.github.io#285]
I want to add a sticky social media sidebar in the home page.
Please assign me this issue. Thanks

**Comment by ArunTeltia** [comment]
Can you explain this issue please I am not sure I totally get what you are trying to do

**Comment by gayatri517** [comment]
![side](https://user-images.githubusercontent.com/70585276/116425209-c1b29d80-a85f-11eb-8e2e-971198d3c6e3.png)
I would like to add this in the homepage.

**Comment by LordShenron** [comment]
Some useless to me

**Comment by ArunTeltia** [comment]
I dont know looks good to me this will looks good on the index page

**Comment by LordShenron** [comment]
@ArunTeltia noob

**Comment by ArunTeltia** [comment]
YOu noob something at the right corner will looks cool, okay i decided he/she is working on it will merge it he/she gets point then revert if it looks boring to you

**Comment by ArunTeltia** [comment]
@gayatri517 go ahead work on it, assigning this one to you

**Comment by LordShenron** [comment]
@ArunTeltia Awwwww nooooo

**Comment by ArunTeltia** [comment]
Message me on whatsapp
