### ISSUE TITLE
Responsiveness to the blog in different viewport

### ISSUE THREAD

**Issue by Samridhi-98** [ProjectSakura/ProjectSakura.github.io#288]
### Evidence / Screenshot (if possible)

![sakura-main](https://user-images.githubusercontent.com/54466041/117202228-34e18400-ae0b-11eb-841d-945f81bbb13e.PNG)

### Steps to Reproduce

1. Press F12 
2. Select iPad from the device section.

**Comment by Samridhi-98** [comment]
@ArunTeltia  @LordShenron  I would like to work on it please assign it to me.

**Comment by ArunTeltia** [comment]
Yup Lets work on this @Samridhi-98  go for it
