### ISSUE TITLE
Adding light and dark mode toggler on blog site.

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/ProjectSakura.github.io#290]
### Describe the problem that you'd like solved
The blog site is only available in dark mode.

### Proposal & Constraints

- [ ] Add dark/light mode toggler on `/blog.html`
- [ ] Add dark/light mode toggler on `/post/xyz.hmtl`(all the pages available on the post folder

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia I would like to work on this issue Kindly assign

**Comment by LordShenron** [comment]
@ritik307 website is already in completely dark mode, So a NO from me.

**Comment by ritik307** [comment]
@LordShenron The site does not have a light mode. That's why I said **toggler**.

**Comment by LordShenron** [comment]
@ritik307 coz a light mode goes against the site guidelines
