### ISSUE TITLE
Removing redundency from blogs

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/ProjectSakura.github.io#291]
### Describe the problem that you'd like solved

- Currently, `blogs.html` is having redundant code for every blog info card and there is an unnecessary `.html` file in the `posts` folder which could be handled in just a single file.
- The above makes it very difficult for the dev to add a new blog to the site.

### Proposal & Constraints

- [ ] Add `.json` file for holding every blog data.
- [ ] Replacing the `post folder`'s files to just a single file retrieving data and iterating over it to generate the blogs from the `JSON`.

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia I would like to work on this issue so plz assign it to me.

**Comment by LordShenron** [comment]
@ritik307 This sound very fascinating but it would take a huge amount of work and will be hard to review too.. plus there could be issues with adsense.

**Comment by LordShenron** [comment]
> @LordShenron Yup that's probably what I was talking about. As far as I know, the ads section won't be affected by it.

You can do it "only" on blog.html. Go ahead with this issue, I am assigning it to you.

**Comment by ritik307** [comment]
@LordShenron sure!

**Comment by ritik307** [comment]
Hi @LordShenron 
While working on this issue I have come up with two solutions:- 

- Revamping the project as a node-based application (**Pros:** will be scale-able for future implementation+faster to build, **Cons:**-no GitHub deployment support.)

- Revamping the project as a React-based application (**Pros:** same as above+CAN be deployed on GitHub, **Cons:**-will take 2-3 days to work on)
Please suggest which one to prefer

**Comment by LordShenron** [comment]
@ritik307 there are some routing issues with react. Think you can really do it?

**Comment by ritik307** [comment]
@LordShenron what kind of routing issues you are talking about?

**Comment by LordShenron** [comment]
@ritik307 Content security restrictions that we are plagued with on our wiki and download page. You can only route traffic to the index and trying to send traffic to a specific page will end up with 404.

**Comment by LordShenron** [comment]
> @LordShenron I am not getting it are you talking about the Link and anchor tag issue? like `Link` can only perform routing within the application and to route to different link outside the scope of the website we have to use the `a` tag. Is this the issue you are referring to?

try visiting https://projectsakura.xyz/download/X00T 
and see console logs

**Comment by ritik307** [comment]
![image](https://user-images.githubusercontent.com/22374829/117542040-7bfe8d80-b034-11eb-95d6-e08ae52294ed.png)
is this the issue you are referring to?

**Comment by LordShenron** [comment]
> ![image](https://user-images.githubusercontent.com/22374829/117542040-7bfe8d80-b034-11eb-95d6-e08ae52294ed.png)
> is this the issue you are referring to?

looks like it;s getting cleaned up coz of our custom 404 page. 
try visiting this page, you can see the issue -> https://projectsakura.xyz/wiki/install-sakura

**Comment by ritik307** [comment]
![image](https://user-images.githubusercontent.com/22374829/117542174-2eceeb80-b035-11eb-8ecb-2b05a5dd9c23.png)
Is this the issue?

**Comment by LordShenron** [comment]
> > > ![image](https://user-images.githubusercontent.com/22374829/117542174-2eceeb80-b035-11eb-8ecb-2b05a5dd9c23.png)
> > > Is this the issue?
> > 
> > 
> > yup
> 
> I am familiar with this issue, It can be fixed using `Hash Router`. I will fix this in wiki and downloads after implementing it on the blogs .

wiki is written in react but download is written in vue.. If you can fix it I will give you 1000billion points out of 100.

**Comment by ritik307** [comment]
@LordShenron I will surely be able to fix it on the `wiki` but for `download` I have to do some research and will try my best to fix it.

**Comment by LordShenron** [comment]
> @LordShenron I will surely be able to fix it on the `wiki` but for `download` I have to do some research and will try my best to fix it.

Go ahead and i will hire you instead of @ArunTeltia  xD.. save your place @ArunTeltia bruu

**Comment by ritik307** [comment]
😂😂😂😂

**Comment by ArunTeltia** [comment]
bruh F

**Comment by ArunTeltia** [comment]
I think we can close this, closing it for now
