### ISSUE TITLE
Ad banners isn't properly displaced

### ISSUE THREAD

**Issue by Alenjojo** [ProjectSakura/ProjectSakura.github.io#292]
### Evidence / Screenshot (if possible)
![Capture](https://user-images.githubusercontent.com/51394913/117565028-e6630c80-b0cc-11eb-9ea7-d23a0c400ab2.PNG)

### Steps to Reproduce

1. Go to the home page
2. The three banners aren't properly positioned

* Actual: I assume i can rearrange the banners into their respective position, so that it would produce a good user interface.
* Expected:

**Comment by AshuKV** [comment]
Hi I am a GSSOC'21 participant. I want to work on this issue under GSSoC'21. Can you please assign it to me?

**Comment by ShrutiKhatri826** [comment]
I would like to contribute to this issue as a GSSOC'21 participant. Please assign it to me, hoping for a positive reply soon.

**Comment by LordShenron** [comment]
You three come to a decision of who should do it.

**Comment by Alenjojo** [comment]
I brought up the issue, so it would be much easier if you could assign it to me
