### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/ProjectSakura.github.io#297]
### Steps to Reproduce

1. Go to `https://projectsakura.xyz/`

* **Actual:** The colour of the navbar doesn't match the overall theme of the site
* **Expected:** The colo should be the same as the footer. 
![image](https://user-images.githubusercontent.com/22374829/118703296-9229fc00-b833-11eb-88e5-9dd152ad1708.png)

* **Actual:** The footer button's colour fades to a darker colour when hover which makes the button difficult to recognise.
* **Expected:** The hover colour on the button should be a bright colour probably `off white`
![image](https://user-images.githubusercontent.com/22374829/118703800-1f6d5080-b834-11eb-951a-df091263f75c.png)

* **Actual:** The card button fades to a darker colour when hover which makes the button difficult to recognise.
* **Expected:** The hover colour on the button should be a bright colour probably `off white`.
![image](https://user-images.githubusercontent.com/22374829/118703941-3e6be280-b834-11eb-8b8d-bef0ef3aeabd.png)

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia Plz assign.

**Comment by LordShenron** [comment]
good to go
