### ISSUE TITLE
Hero image is stretching

### ISSUE THREAD

**Issue by rbattiato** [ProjectSakura/ProjectSakura.github.io#305]
Hi! I'm new to open source, I'm sorry if I'm doing something wrong.
I see the hero phone image is stretching on desktop, because both image width and height have been set.
I've cloned the repo, created a new branch `fix/hero` and applied a fix that works on [modern browsers](https://caniuse.com/?search=object-fit). However I don't have the permission to push my branch and then open a PR.

What should I do next?

Thanks

**Comment by LordShenron** [comment]
Fork this repo and then push your changes to it. After that create a pull request and we will review it. 

References in case you need some: 
https://docs.github.com/en/get-started/quickstart/fork-a-repo

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ArunTeltia** [comment]
Hello @rbattiato welcome to project sakura community, 
Yes I just checked this and this is a valid issue, 

As @LordShenron said you can start by forking this repo and then can create a pull request to the main repo and then you can start contributing to the open source 

Let me, @LordShenron or @ritik307  know if you have any issues regarding creating an PR , we will try our best to help you

Happy Open Source

**Comment by rbattiato** [comment]
Thank you! All done.
