### ISSUE TITLE
Homepage broken / redirect to malware website

### ISSUE THREAD

**Issue by rnwelsh** [ProjectSakura/ProjectSakura.github.io#310]
### Evidence / Screenshot (if possible)
![image](https://github.com/ProjectSakura/ProjectSakura.github.io/assets/61340456/3f883978-e9e3-4b5e-9af3-89ae12e5900a)

### Steps to Reproduce

1. Go to github.com/ProjectSakura/ProjectSakura.github.io
2. Click link to projectsakura.xyz

* Actual: broken site / malware site opens
* Expected: the home page to this website opens

### Details

- **Browser type/version?**  Microsoft Edge 113.0.1774.57 Official Build
- **Operating system?** Windows Home 22621.1778

### Proposal & Constraints

remove the broken link

**Comment by Darkstar085** [comment]
@rnwelsh Project discontinued..

**Comment by ReveRTX** [comment]
**Our website is now live at : [ProjectSakura.me](projectsakura.me)**

**Comment by Fabian42** [comment]
@ReveRTX That one forwards me a million times, gets blocked twice by the ad/phishing blocker and then wants me to buy a bikini. Hmmm, surely this is trustworthy…
